player_models:
  - provider: "groq"
    model_id: "llama-3.3-70b-versatile"
  - provider: "cerebras"
    model_id: "llama-3.3-70b"
  - provider: "groq"
    model_id: "qwen/qwen3-32b"
  - provider: "cerebras"
    model_id: "qwen-3-32b"
  - provider: "groq"
    model_id: "meta-llama/llama-4-maverick-17b-128e-instruct"
  - provider: "groq"
    model_id: "meta-llama/llama-4-scout-17b-16e-instruct"
  - provider: "groq"
    model_id: "moonshotai/kimi-k2-instruct-0905"
  - provider: "groq"
    model_id: "moonshotai/kimi-k2-instruct"

director_models:
  - provider: "groq"
    model_id: "llama-3.3-70b-versatile"
  - provider: "cerebras"
    model_id: "llama3.1-8b"